// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// stc_engine_new
SEXP stc_engine_new(Rcpp::NumericVector x1, Rcpp::NumericVector x2, Rcpp::IntegerVector ids, Rcpp::List plan, Rcpp::NumericVector deltas, int cor_mode, double seed, bool noise_supplied, int n_threads, int chunk, bool keep_surrogates);
RcppExport SEXP _STcompare_stc_engine_new(SEXP x1SEXP, SEXP x2SEXP, SEXP idsSEXP, SEXP planSEXP, SEXP deltasSEXP, SEXP cor_modeSEXP, SEXP seedSEXP, SEXP noise_suppliedSEXP, SEXP n_threadsSEXP, SEXP chunkSEXP, SEXP keep_surrogatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type plan(planSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type deltas(deltasSEXP);
    Rcpp::traits::input_parameter< int >::type cor_mode(cor_modeSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type noise_supplied(noise_suppliedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_surrogates(keep_surrogatesSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_engine_new(x1, x2, ids, plan, deltas, cor_mode, seed, noise_supplied, n_threads, chunk, keep_surrogates));
    return rcpp_result_gen;
END_RCPP
}
// stc_engine_deltas
Rcpp::List stc_engine_deltas(SEXP session);
RcppExport SEXP _STcompare_stc_engine_deltas(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_engine_deltas(session));
    return rcpp_result_gen;
END_RCPP
}
// stc_engine_define
Rcpp::List stc_engine_define(SEXP session, Rcpp::NumericMatrix pool, Rcpp::IntegerVector task_source, Rcpp::List task_grid, Rcpp::List task_targets, Rcpp::List task_rabs, Rcpp::IntegerVector task_unit, Rcpp::LogicalVector unit_fail_on_dir);
RcppExport SEXP _STcompare_stc_engine_define(SEXP sessionSEXP, SEXP poolSEXP, SEXP task_sourceSEXP, SEXP task_gridSEXP, SEXP task_targetsSEXP, SEXP task_rabsSEXP, SEXP task_unitSEXP, SEXP unit_fail_on_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pool(poolSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type task_source(task_sourceSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type task_grid(task_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type task_targets(task_targetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type task_rabs(task_rabsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type task_unit(task_unitSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type unit_fail_on_dir(unit_fail_on_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_engine_define(session, pool, task_source, task_grid, task_targets, task_rabs, task_unit, unit_fail_on_dir));
    return rcpp_result_gen;
END_RCPP
}
// stc_engine_run
void stc_engine_run(SEXP session, Rcpp::IntegerVector units, int b_from, int b_to, Rcpp::IntegerMatrix perm, SEXP noise, double h, int n_max);
RcppExport SEXP _STcompare_stc_engine_run(SEXP sessionSEXP, SEXP unitsSEXP, SEXP b_fromSEXP, SEXP b_toSEXP, SEXP permSEXP, SEXP noiseSEXP, SEXP hSEXP, SEXP n_maxSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type units(unitsSEXP);
    Rcpp::traits::input_parameter< int >::type b_from(b_fromSEXP);
    Rcpp::traits::input_parameter< int >::type b_to(b_toSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type perm(permSEXP);
    Rcpp::traits::input_parameter< SEXP >::type noise(noiseSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n_max(n_maxSEXP);
    stc_engine_run(session, units, b_from, b_to, perm, noise, h, n_max);
    return R_NilValue;
END_RCPP
}
// stc_engine_units
Rcpp::List stc_engine_units(SEXP session);
RcppExport SEXP _STcompare_stc_engine_units(SEXP sessionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_engine_units(session));
    return rcpp_result_gen;
END_RCPP
}
// stc_engine_task_results
Rcpp::List stc_engine_task_results(SEXP session, Rcpp::IntegerVector tasks, bool surrogates);
RcppExport SEXP _STcompare_stc_engine_task_results(SEXP sessionSEXP, SEXP tasksSEXP, SEXP surrogatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tasks(tasksSEXP);
    Rcpp::traits::input_parameter< bool >::type surrogates(surrogatesSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_engine_task_results(session, tasks, surrogates));
    return rcpp_result_gen;
END_RCPP
}
// stc_engine_set_threads
void stc_engine_set_threads(SEXP session, int n_threads, int chunk);
RcppExport SEXP _STcompare_stc_engine_set_threads(SEXP sessionSEXP, SEXP n_threadsSEXP, SEXP chunkSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< SEXP >::type session(sessionSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type chunk(chunkSEXP);
    stc_engine_set_threads(session, n_threads, chunk);
    return R_NilValue;
END_RCPP
}
// stc_parallel_selftest
Rcpp::IntegerVector stc_parallel_selftest(int n_items, int n_threads, int fail_item, int sleep_ms);
RcppExport SEXP _STcompare_stc_parallel_selftest(SEXP n_itemsSEXP, SEXP n_threadsSEXP, SEXP fail_itemSEXP, SEXP sleep_msSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type n_items(n_itemsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type fail_item(fail_itemSEXP);
    Rcpp::traits::input_parameter< int >::type sleep_ms(sleep_msSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_parallel_selftest(n_items, n_threads, fail_item, sleep_ms));
    return rcpp_result_gen;
END_RCPP
}
// stc_variog_pairs
Rcpp::List stc_variog_pairs(Rcpp::NumericVector x1, Rcpp::NumericVector x2, double max_dist, Rcpp::NumericVector lims, bool keep_nugget, int pairs_min);
RcppExport SEXP _STcompare_stc_variog_pairs(SEXP x1SEXP, SEXP x2SEXP, SEXP max_distSEXP, SEXP limsSEXP, SEXP keep_nuggetSEXP, SEXP pairs_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lims(limsSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_nugget(keep_nuggetSEXP);
    Rcpp::traits::input_parameter< int >::type pairs_min(pairs_minSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_variog_pairs(x1, x2, max_dist, lims, keep_nugget, pairs_min));
    return rcpp_result_gen;
END_RCPP
}
// stc_variog_eval
Rcpp::NumericMatrix stc_variog_eval(Rcpp::List plan, Rcpp::NumericMatrix Z, int tile);
RcppExport SEXP _STcompare_stc_variog_eval(SEXP planSEXP, SEXP ZSEXP, SEXP tileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type plan(planSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type tile(tileSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_variog_eval(plan, Z, tile));
    return rcpp_result_gen;
END_RCPP
}
// stc_smoother
Rcpp::List stc_smoother(Rcpp::NumericVector x1, Rcpp::NumericVector x2, double delta, int maxk, bool build_operator);
RcppExport SEXP _STcompare_stc_smoother(SEXP x1SEXP, SEXP x2SEXP, SEXP deltaSEXP, SEXP maxkSEXP, SEXP build_operatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxk(maxkSEXP);
    Rcpp::traits::input_parameter< bool >::type build_operator(build_operatorSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_smoother(x1, x2, delta, maxk, build_operator));
    return rcpp_result_gen;
END_RCPP
}
// stc_smoother_fitted_exact
Rcpp::List stc_smoother_fitted_exact(Rcpp::NumericVector x1, Rcpp::NumericVector x2, Rcpp::NumericVector y, double delta, int maxk);
RcppExport SEXP _STcompare_stc_smoother_fitted_exact(SEXP x1SEXP, SEXP x2SEXP, SEXP ySEXP, SEXP deltaSEXP, SEXP maxkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxk(maxkSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_smoother_fitted_exact(x1, x2, y, delta, maxk));
    return rcpp_result_gen;
END_RCPP
}
// stc_smoother_apply
Rcpp::NumericMatrix stc_smoother_apply(Rcpp::List op, Rcpp::NumericMatrix Y, Rcpp::Nullable<Rcpp::IntegerVector> rows, bool blocked);
RcppExport SEXP _STcompare_stc_smoother_apply(SEXP opSEXP, SEXP YSEXP, SEXP rowsSEXP, SEXP blockedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type op(opSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< bool >::type blocked(blockedSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_smoother_apply(op, Y, rows, blocked));
    return rcpp_result_gen;
END_RCPP
}
// stc_lecuyer_seed
Rcpp::NumericVector stc_lecuyer_seed(int seed);
RcppExport SEXP _STcompare_stc_lecuyer_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_lecuyer_seed(seed));
    return rcpp_result_gen;
END_RCPP
}
// stc_lecuyer_runif
Rcpp::NumericVector stc_lecuyer_runif(int seed, int n);
RcppExport SEXP _STcompare_stc_lecuyer_runif(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_lecuyer_runif(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// stc_lecuyer_rnorm
Rcpp::NumericVector stc_lecuyer_rnorm(int seed, int n);
RcppExport SEXP _STcompare_stc_lecuyer_rnorm(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_lecuyer_rnorm(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// stc_legacy_noise
Rcpp::NumericMatrix stc_legacy_noise(int seed, int N, int K);
RcppExport SEXP _STcompare_stc_legacy_noise(SEXP seedSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_legacy_noise(seed, N, K));
    return rcpp_result_gen;
END_RCPP
}
// stc_cor_cols
Rcpp::NumericVector stc_cor_cols(Rcpp::NumericMatrix X, Rcpp::NumericVector y, int mode);
RcppExport SEXP _STcompare_stc_cor_cols(SEXP XSEXP, SEXP ySEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_cor_cols(X, y, mode));
    return rcpp_result_gen;
END_RCPP
}
// stc_ols
Rcpp::List stc_ols(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _STcompare_stc_ols(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(stc_ols(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STcompare_stc_engine_new", (DL_FUNC) &_STcompare_stc_engine_new, 11},
    {"_STcompare_stc_engine_deltas", (DL_FUNC) &_STcompare_stc_engine_deltas, 1},
    {"_STcompare_stc_engine_define", (DL_FUNC) &_STcompare_stc_engine_define, 8},
    {"_STcompare_stc_engine_run", (DL_FUNC) &_STcompare_stc_engine_run, 8},
    {"_STcompare_stc_engine_units", (DL_FUNC) &_STcompare_stc_engine_units, 1},
    {"_STcompare_stc_engine_task_results", (DL_FUNC) &_STcompare_stc_engine_task_results, 3},
    {"_STcompare_stc_engine_set_threads", (DL_FUNC) &_STcompare_stc_engine_set_threads, 3},
    {"_STcompare_stc_parallel_selftest", (DL_FUNC) &_STcompare_stc_parallel_selftest, 4},
    {"_STcompare_stc_variog_pairs", (DL_FUNC) &_STcompare_stc_variog_pairs, 6},
    {"_STcompare_stc_variog_eval", (DL_FUNC) &_STcompare_stc_variog_eval, 3},
    {"_STcompare_stc_smoother", (DL_FUNC) &_STcompare_stc_smoother, 5},
    {"_STcompare_stc_smoother_fitted_exact", (DL_FUNC) &_STcompare_stc_smoother_fitted_exact, 5},
    {"_STcompare_stc_smoother_apply", (DL_FUNC) &_STcompare_stc_smoother_apply, 4},
    {"_STcompare_stc_lecuyer_seed", (DL_FUNC) &_STcompare_stc_lecuyer_seed, 1},
    {"_STcompare_stc_lecuyer_runif", (DL_FUNC) &_STcompare_stc_lecuyer_runif, 2},
    {"_STcompare_stc_lecuyer_rnorm", (DL_FUNC) &_STcompare_stc_lecuyer_rnorm, 2},
    {"_STcompare_stc_legacy_noise", (DL_FUNC) &_STcompare_stc_legacy_noise, 3},
    {"_STcompare_stc_cor_cols", (DL_FUNC) &_STcompare_stc_cor_cols, 3},
    {"_STcompare_stc_ols", (DL_FUNC) &_STcompare_stc_ols, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_STcompare(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
