// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// stc_variog_pairs
Rcpp::List stc_variog_pairs(Rcpp::NumericVector x1, Rcpp::NumericVector x2, double max_dist, Rcpp::NumericVector lims, bool keep_nugget, int pairs_min);
RcppExport SEXP _STcompare_stc_variog_pairs(SEXP x1SEXP, SEXP x2SEXP, SEXP max_distSEXP, SEXP limsSEXP, SEXP keep_nuggetSEXP, SEXP pairs_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lims(limsSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_nugget(keep_nuggetSEXP);
    Rcpp::traits::input_parameter< int >::type pairs_min(pairs_minSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_variog_pairs(x1, x2, max_dist, lims, keep_nugget, pairs_min));
    return rcpp_result_gen;
END_RCPP
}
// stc_variog_eval
Rcpp::NumericMatrix stc_variog_eval(Rcpp::List plan, Rcpp::NumericMatrix Z, int tile);
RcppExport SEXP _STcompare_stc_variog_eval(SEXP planSEXP, SEXP ZSEXP, SEXP tileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type plan(planSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type tile(tileSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_variog_eval(plan, Z, tile));
    return rcpp_result_gen;
END_RCPP
}
// stc_smoother
Rcpp::List stc_smoother(Rcpp::NumericVector x1, Rcpp::NumericVector x2, double delta, int maxk, bool build_operator);
RcppExport SEXP _STcompare_stc_smoother(SEXP x1SEXP, SEXP x2SEXP, SEXP deltaSEXP, SEXP maxkSEXP, SEXP build_operatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxk(maxkSEXP);
    Rcpp::traits::input_parameter< bool >::type build_operator(build_operatorSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_smoother(x1, x2, delta, maxk, build_operator));
    return rcpp_result_gen;
END_RCPP
}
// stc_smoother_fitted_exact
Rcpp::List stc_smoother_fitted_exact(Rcpp::NumericVector x1, Rcpp::NumericVector x2, Rcpp::NumericVector y, double delta, int maxk);
RcppExport SEXP _STcompare_stc_smoother_fitted_exact(SEXP x1SEXP, SEXP x2SEXP, SEXP ySEXP, SEXP deltaSEXP, SEXP maxkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxk(maxkSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_smoother_fitted_exact(x1, x2, y, delta, maxk));
    return rcpp_result_gen;
END_RCPP
}
// stc_smoother_apply
Rcpp::NumericMatrix stc_smoother_apply(Rcpp::List op, Rcpp::NumericMatrix Y, Rcpp::Nullable<Rcpp::IntegerVector> rows);
RcppExport SEXP _STcompare_stc_smoother_apply(SEXP opSEXP, SEXP YSEXP, SEXP rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type op(opSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type rows(rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_smoother_apply(op, Y, rows));
    return rcpp_result_gen;
END_RCPP
}
// stc_lecuyer_seed
Rcpp::NumericVector stc_lecuyer_seed(int seed);
RcppExport SEXP _STcompare_stc_lecuyer_seed(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_lecuyer_seed(seed));
    return rcpp_result_gen;
END_RCPP
}
// stc_lecuyer_runif
Rcpp::NumericVector stc_lecuyer_runif(int seed, int n);
RcppExport SEXP _STcompare_stc_lecuyer_runif(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_lecuyer_runif(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// stc_lecuyer_rnorm
Rcpp::NumericVector stc_lecuyer_rnorm(int seed, int n);
RcppExport SEXP _STcompare_stc_lecuyer_rnorm(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_lecuyer_rnorm(seed, n));
    return rcpp_result_gen;
END_RCPP
}
// stc_legacy_noise
Rcpp::NumericMatrix stc_legacy_noise(int seed, int N, int K);
RcppExport SEXP _STcompare_stc_legacy_noise(SEXP seedSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_legacy_noise(seed, N, K));
    return rcpp_result_gen;
END_RCPP
}
// stc_cor_cols
Rcpp::NumericVector stc_cor_cols(Rcpp::NumericMatrix X, Rcpp::NumericVector y, int mode);
RcppExport SEXP _STcompare_stc_cor_cols(SEXP XSEXP, SEXP ySEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(stc_cor_cols(X, y, mode));
    return rcpp_result_gen;
END_RCPP
}
// stc_ols
Rcpp::List stc_ols(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _STcompare_stc_ols(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(stc_ols(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_STcompare_stc_variog_pairs", (DL_FUNC) &_STcompare_stc_variog_pairs, 6},
    {"_STcompare_stc_variog_eval", (DL_FUNC) &_STcompare_stc_variog_eval, 3},
    {"_STcompare_stc_smoother", (DL_FUNC) &_STcompare_stc_smoother, 5},
    {"_STcompare_stc_smoother_fitted_exact", (DL_FUNC) &_STcompare_stc_smoother_fitted_exact, 5},
    {"_STcompare_stc_smoother_apply", (DL_FUNC) &_STcompare_stc_smoother_apply, 3},
    {"_STcompare_stc_lecuyer_seed", (DL_FUNC) &_STcompare_stc_lecuyer_seed, 1},
    {"_STcompare_stc_lecuyer_runif", (DL_FUNC) &_STcompare_stc_lecuyer_runif, 2},
    {"_STcompare_stc_lecuyer_rnorm", (DL_FUNC) &_STcompare_stc_lecuyer_rnorm, 2},
    {"_STcompare_stc_legacy_noise", (DL_FUNC) &_STcompare_stc_legacy_noise, 3},
    {"_STcompare_stc_cor_cols", (DL_FUNC) &_STcompare_stc_cor_cols, 3},
    {"_STcompare_stc_ols", (DL_FUNC) &_STcompare_stc_ols, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_STcompare(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
