# The compiled engine behind viladomatCorrelation(), spatialCorrelation(), spatialCorrelationGeneExp(),
# spatialCorrelationGeneExpIterPermutations() and spatialCorrelationGeneExpWithinSample()
# (dev/engine-spec.md). The engine is the only implementation of the Viladomat null: the original R
# implementation (locfit, geoR and BiocParallel::bplapply()) was removed, and its results survive as the
# test fixtures and the published results in bench/published, which the engine reproduces.
#
# This file holds the R side of the engine. The C++ entry points are in R/RcppExports.R (generated from
# src/stc_rcpp.cpp and src/stc_engine_rcpp.cpp). All names start with a dot and none is exported (the
# NAMESPACE, generated by roxygen2, exports only the functions tagged @export).
#
# Building blocks (each verified against the R code it replaces, tests/testthat/test-cpp-components.R):
#   .stc_variog_plan()      R part of geoR::variog() (umax, nugget flag, bin limits) + C++ pair table
#   .stc_variog_eval()      variograms of many data vectors with a plan (C++)
#   .stc_smoother()         locfit's tree and the factored smoothing operator (C++)
#   .stc_smoother_apply()   apply the operator to a block of columns (C++)
#   .stc_smoother_fitted_exact()  exact replica of fitted(locfit(...)), for tests (C++)
#   .stc_lecuyer_rnorm(), .stc_legacy_noise()  R-compatible L'Ecuyer-CMRG normals (C++)
#   .stc_cor_cols()         R's cor(X, y), column by column (C++); .stc_cor_mode() picks its mode
#   .stc_ols()              lm(y ~ 1 + x) coefficients by the closed form (C++)
#
# The engine (dev/engine-spec.md sections 2, 3 and 6; tests/testthat/test-engine.R):
#   .stc_rng_save(), .stc_rng_restore(), .stc_local_rng()   keep the caller's global RNG state
#   .stc_legacy_stream(), .stc_stream_perms(), .stc_stream_noise()   the legacy random draws, in batches
#   .stc_subsample()        the variogram subsample of runs with independent streams (compareSpatial())
#   .stc_threads()          number of worker threads from nThreads or BPPARAM
#   .stc_engine_correlate() null correlations, delta* and p-values of many genes (C++ engine)
#   .stc_engine_prepare(), .stc_engine_extend()   its steps, also used by compareSpatial() (R/compareSpatial.R)
#
# The exported functions (R/spatialCorrelation.R, R/iterativePermutations.R) share the helpers at the end
# of this file: argument checks, cor.test()'s estimates and p-values, the result table and the NA-row warnings.

# Session cache of the engine (results of one-off probes).
.stc_engine_cache <- new.env(parent = emptyenv())

# Pair table of
#   geoR::variog(coords = cbind(long, lat), data = z, max.dist = max_dist, option = "bin")
# (every other argument at its default; geoR 1.9-6) for fixed coordinates, so that
# .stc_variog_eval(plan, Z) returns the same u, n and v as geoR for every column of Z.
#
# long, lat: coordinates of the (subsampled) points in geoR's column order, as STcompare passes
#   them (coords = cbind(long[ids], lat[ids]) with lat = pos[, 1] and long = pos[, 2]).
# max_dist: the max.dist STcompare passes, quantile(dist(cbind(lat, long)), maxDistPrctile).
#
# Everything geoR computes with R's own dist() is computed here with dist(), so it follows the
# running R build (dist() uses a fused multiply-add on some platforms, and on lattices many pairs
# tie with umax to the last bit; dev/investigation/02-geoR-variogram.md):
#   u <- dist(coords); nugget <- min(u) < 1e-12; umax <- max(u[u < max.dist])  (variogram.R:93-119)
#   bins.lim <- seq(0, umax, length.out = 14); bins.lim <- c(0, 1e-12, bins.lim[bins.lim > 1e-12])
#   u (centres) <- 0.5 * (bins.lim[-1] + bins.lim[-length(bins.lim)])          (.define.bins())
#   bins.lim[1] <- -1                                                           (variogram.R:127)
# The C++ part then runs geoR's binit() loop with hypot() (src/geoR.c:370-422).
#
# Returns a list:
#   ok, reason   ok = FALSE where geoR::variog() itself fails (no pair closer than max.dist; or
#                co-located points with fewer than two bins kept, where variogram.R:255 fails);
#   nbins, u, n  the bins geoR returns (n >= 2 pairs; the nugget bin only with co-located points);
#   bins_lim     geoR's $bins.lim;
#   ptr, i, j    the pairs of each bin in geoR's summation order (CSR, 0-based point indices);
#   bin          geoR's bin index of each returned bin (0 = nugget bin);
#   umax, max_dist, nugget, lims, npoints, npairs_le_maxdist.
# Unlike geoR, nothing is printed for co-located points.
.stc_variog_plan <- function(long, lat, max_dist) {
  long <- as.double(long)
  lat <- as.double(lat)
  max_dist <- as.double(max_dist)  # quantile() names its value; geoR passes as.double(max.dist)
  if (length(long) != length(lat)) stop("long and lat must have the same length")
  if (length(long) < 2L) stop("the variogram needs at least 2 points")
  if (length(max_dist) != 1L || is.na(max_dist)) stop("max_dist must be a single number")
  if (!all(is.finite(long)) || !all(is.finite(lat))) stop("coordinates must be finite")
  fail <- function(reason) {
    list(ok = FALSE, reason = reason, nbins = 0L, u = numeric(0), n = numeric(0),
         npoints = length(long), max_dist = max_dist)
  }
  u <- as.vector(stats::dist(cbind(long, lat)))
  nugget <- min(u) < 1e-12
  below <- u[u < max_dist]
  if (!length(below)) return(fail("no pair of points is closer than max.dist"))
  umax <- max(below)
  bins_lim <- seq(0, umax, length.out = 14)
  bins_lim <- c(0, 1e-12, bins_lim[bins_lim > 1e-12])
  centres <- 0.5 * (bins_lim[-1] + bins_lim[-length(bins_lim)])
  lims <- bins_lim
  if (lims[1] < 1e-16) lims[1] <- -1
  tab <- .stc_variog_pairs(long, lat, max_dist, lims, nugget, 2L)
  u_out <- centres[tab$bin + 1L]
  if (nugget) {
    # variogram.R:252-257: with co-located points geoR replaces the second centre when the first two
    # are below 1e-11, and fails (an NA condition) when fewer than two bins are left
    first2 <- all(u_out[1:2] < 1e-11)
    if (is.na(first2)) return(fail("co-located points and fewer than two variogram bins"))
    if (first2) u_out[2] <- sum(bins_lim[2:3]) / 2
  }
  list(ok = TRUE, reason = "", nbins = length(tab$n), u = u_out, n = tab$n,
       bins_lim = if (nugget) bins_lim else bins_lim[-1],
       ptr = tab$ptr, i = tab$i, j = tab$j, bin = tab$bin,
       umax = umax, max_dist = max_dist, nugget = nugget, lims = lims,
       npoints = length(long), npairs_le_maxdist = tab$npairs_le_maxdist)
}

# The arithmetic mode of .stc_cor_cols() for this machine (see src/stc_stats.h): 0 R's code as
# written (long double), 1 every accumulation fused, 2 the pattern of CRAN's R for macOS arm64, 3 double
# accumulators (R built with --disable-long-double). It compares cor() with the C++ code on fixed probes
# once per session and returns the first of modes 0, 2, 1 and 3 that reproduces cor() bit for bit
# (attribute exact = TRUE). If none does, it returns 0 when that agrees with cor() to 1e-14, and
# otherwise 3, the mode without x87 arithmetic (Rosetta 2 mis-executes the long double code; exact =
# FALSE in both cases; mode 3 then agrees with cor() to a few 1e-15).
.stc_cor_mode <- function() {
  if (is.null(.stc_engine_cache$cor_mode)) {
    probe <- function(n) {
      k <- seq_len(n)
      y <- sin(0.731 * k) * 3 + k / 17
      X <- vapply(seq_len(12), function(j) cos(k * (0.37 + j / 11)) + sin(j * k / 5) / (j + 1) + k * j / 1000,
                  numeric(n))
      list(X = X, y = y, r = as.vector(stats::cor(X, y)))
    }
    probes <- lapply(c(69L, 64L, 7L), probe)
    exact <- function(mode) all(vapply(probes, function(p) identical(.stc_cor_cols(p$X, p$y, mode), p$r), NA))
    maxdiff <- function(mode) max(vapply(probes, function(p) max(abs(.stc_cor_cols(p$X, p$y, mode) - p$r)), 0))
    mode <- NA_integer_
    for (m in c(0L, 2L, 1L, 3L)) {
      if (exact(m)) {
        mode <- m
        break
      }
    }
    is_exact <- !is.na(mode)
    if (!is_exact) mode <- if (isTRUE(maxdiff(0L) <= 1e-14)) 0L else 3L
    .stc_engine_cache$cor_mode <- structure(mode, exact = is_exact)
  }
  .stc_engine_cache$cor_mode
}

# ---------------------------------------------------------------------------------------------------
# The caller's global RNG state
# ---------------------------------------------------------------------------------------------------

# The RNG kinds and .Random.seed (NULL when there is none). RNGkind() as a query does not create
# .Random.seed.
.stc_rng_save <- function() {
  list(kind = RNGkind(), seed = get0(".Random.seed", envir = globalenv(), inherits = FALSE))
}

# Put back a state from .stc_rng_save(): first the kinds (RNGkind() re-seeds the generator and writes
# .Random.seed), then .Random.seed itself, or no .Random.seed if there was none. sample.kind =
# "Rounding" warns when it is set; that warning is not repeated here.
.stc_rng_restore <- function(state) {
  suppressWarnings(RNGkind(state$kind[1], state$kind[2], state$kind[3]))
  if (is.null(state$seed)) {
    if (exists(".Random.seed", envir = globalenv(), inherits = FALSE)) {
      rm(".Random.seed", envir = globalenv())
    }
  } else {
    assign(".Random.seed", state$seed, envir = globalenv())
  }
  invisible(NULL)
}

# Save the RNG state now and put it back when the calling function exits, however it exits.
.stc_local_rng <- function(envir = parent.frame()) {
  state <- .stc_rng_save()
  do.call(base::on.exit, list(as.call(list(.stc_rng_restore, state)), add = TRUE), envir = envir)
  invisible(state)
}

# ---------------------------------------------------------------------------------------------------
# The random draws (dev/engine-spec.md 2.1 and 2.6)
# ---------------------------------------------------------------------------------------------------
#
# The streams are those of the original R implementation, so that the published results reproduce:
#   - permutations: set.seed(seed) under the RNG kinds of the calling session, the variogram subsample
#     sample(N, 1000) when N > 1000, then sample.int(N, N) for permutation b = 1, 2, ... (drawn in R);
#   - noise: permutation b uses set.seed(seed + b) under L'Ecuyer-CMRG with Inversion normals, then one
#     rnorm(N) per position of the delta grid (drawn in C++, src/stc_rng.h). The original code drew
#     these inside BiocParallel tasks, whose RNG kinds are always L'Ecuyer-CMRG and Inversion
#     (BiocParallel 1.44), whatever the session's normal.kind; the engine keeps that definition.

# The permutation stream for N pixels: set.seed(seed) under the RNG kinds in
# use now; ids <- sample(N, 1000) if N > 1000 (else 1:N); then permutation b is sample.int(N, N) (what
# sample(X) draws) for b = 1, 2, .... An environment that keeps the stream's own .Random.seed between
# batches (.stc_stream_perms()); the caller's RNG state is restored after every use.
.stc_legacy_stream <- function(N, seed) {
  .stc_local_rng()
  set.seed(seed)
  ids <- if (N > 1000) sample(N, 1000) else seq_len(N)
  s <- new.env(parent = emptyenv())
  s$N <- as.integer(N)
  s$seed <- seed
  s$ids <- ids
  s$kind <- RNGkind()
  s$start <- get(".Random.seed", envir = globalenv(), inherits = FALSE)  # permutation 1 comes next
  s$state <- s$start
  s$next_b <- 1L
  s
}

# Permutation indices b_from..b_to of a stream: an N x (b_to - b_from + 1) integer matrix. Batches are
# drawn in order; an earlier start replays the stream from permutation 1 (prefix property).
.stc_stream_perms <- function(s, b_from, b_to) {
  .stc_local_rng()
  b_from <- as.integer(b_from)
  b_to <- as.integer(b_to)
  N <- s$N
  state <- s$state
  next_b <- s$next_b
  if (b_from < next_b) {
    state <- s$start
    next_b <- 1L
  }
  assign(".Random.seed", state, envir = globalenv())
  while (next_b < b_from) {
    sample.int(N, N)
    next_b <- next_b + 1L
  }
  P <- matrix(0L, N, b_to - b_from + 1L)
  for (j in seq_len(ncol(P))) P[, j] <- sample.int(N, N)
  s$state <- get(".Random.seed", envir = globalenv(), inherits = FALSE)
  s$next_b <- b_to + 1L
  P
}

# The variogram subsample of a run with independent streams (compareSpatial()): sample(N, 1000) after
# set.seed(seed) under R's default RNG kinds (Mersenne-Twister, Inversion, Rejection) when N > 1000, else
# 1:N. This is the legacy plan's subsample under the default kinds; fixing the kinds makes it depend on the
# seed only. The caller's RNG state is restored.
.stc_subsample <- function(N, seed) {
  if (N <= 1000) return(seq_len(N))
  .stc_local_rng()
  RNGkind("Mersenne-Twister", "Inversion", "Rejection")
  set.seed(seed)
  sample(N, 1000)
}

# The noise of permutations b_from..b_to drawn with R's own rnorm() instead of the C++ generator (noise =
# "R" in .stc_engine_correlate(); slow, for tests of the C++ stream): set.seed(seed + b) under
# L'Ecuyer-CMRG with Inversion normals, then K draws of rnorm(N), one per position of a delta grid.
# Returns an N x K x (b_to - b_from + 1) array.
.stc_stream_noise <- function(s, b_from, b_to, K) {
  .stc_local_rng()
  RNGkind("L'Ecuyer-CMRG", "Inversion")
  N <- s$N
  nb <- as.integer(b_to - b_from + 1L)
  out <- array(0, c(N, K, nb))
  for (p in seq_len(nb)) {
    set.seed(s$seed + (b_from + p - 1L))
    for (k in seq_len(K)) out[, k, p] <- stats::rnorm(N)
  }
  out
}

# ---------------------------------------------------------------------------------------------------
# Threads
# ---------------------------------------------------------------------------------------------------

# Number of worker threads of the compiled engine: bpnworkers(BPPARAM) when BPPARAM is given (the
# engine never forks; BPPARAM only says how many cores to use), otherwise nThreads.
.stc_threads <- function(nThreads = 1L, BPPARAM = NULL) {
  n <- if (!is.null(BPPARAM)) BiocParallel::bpnworkers(BPPARAM) else nThreads
  if (!is.numeric(n) || length(n) != 1L || is.na(n) || n < 1 || n != round(n) || n > .Machine$integer.max) {
    stop("the number of threads must be a positive integer")
  }
  as.integer(n)
}

# ---------------------------------------------------------------------------------------------------
# The engine (dev/engine-spec.md sections 2, 3 and 6)
# ---------------------------------------------------------------------------------------------------

.stc_positive_int <- function(x, name) {
  v <- suppressWarnings(as.integer(x))
  if (length(x) != 1L || is.na(v) || v < 1L || v != x) stop(sprintf("%s must be a positive integer", name))
  v
}

# The streams call set.seed(seed) and set.seed(seed + b) for b = 1..B; both must be valid integers.
.stc_check_seed <- function(seed, n_max) {
  if (!is.numeric(seed) || length(seed) != 1L || !is.finite(seed) ||
      anyNA(suppressWarnings(as.integer(c(seed, seed + 1, seed + n_max))))) {
    stop("seed must be a single number such that seed and seed + nPermutations are valid integers")
  }
  invisible(TRUE)
}

# A data matrix with pixels in rows and genes in columns (a vector is one gene).
.stc_gene_matrix <- function(X, name) {
  if (is.null(X)) stop(sprintf("%s is missing", name))
  if (is.null(dim(X))) X <- matrix(X, ncol = 1L)
  X <- as.matrix(X)
  if (!is.numeric(X) && !is.logical(X)) stop(sprintf("%s must be numeric", name))
  storage.mode(X) <- "double"
  X
}

# One delta grid per gene: NULL is the default seq(0.1, 0.9, 0.1) (as in spatialCorrelation()), a vector
# is used for every gene, and a list gives one grid per gene (a NULL element takes the default).
.stc_delta_grids <- function(delta, G, name) {
  default <- seq(0.1, 0.9, 0.1)
  if (is.null(delta)) delta <- default
  if (!is.list(delta)) delta <- rep(list(delta), G)
  if (length(delta) != G) {
    stop(sprintf("%s must be a numeric vector or a list with one element per gene", name))
  }
  lapply(delta, function(d) {
    if (is.null(d)) d <- default
    if (!(is.numeric(d) || (is.logical(d) && all(is.na(d)))) || !length(d)) {
      stop(sprintf("every element of %s must be a non-empty numeric vector", name))
    }
    as.double(d)
  })
}

# Largest batch (permutations) for a memory budget on the batch's noise and permutation indices
# (option STcompare.engine_batch_bytes, default 256 MiB). With independent streams a batch needs no such
# buffers; its size then only sets how often units are scanned (and progress reported): 1024.
.stc_max_batch <- function(state) {
  if (is.null(state$stream)) return(1024L)
  budget <- getOption("STcompare.engine_batch_bytes", 256 * 2^20)
  per <- 8 * state$N * max(1L, state$kmax) * (if (state$noise_R) 2 else 1) + 4 * state$N
  max(1L, as.integer(min(.Machine$integer.max, floor(budget / per))))
}

# Null correlations, delta* and permutation p-values of many genes with the compiled engine (the
# Viladomat null of viladomatCorrelation() in both directions for every gene, with one seed).
#
# X, Y      pixels x genes matrices (the shared pixels of the two samples; a vector is one gene).
# pos       pixels x 2 coordinates (lat = pos[, 1], long = pos[, 2], the names the method uses).
# deltaX, deltaY  delta grids: NULL (default grid), one vector for every gene, or a list per gene.
# nPermutations   permutations per gene (fixed B), or, with adaptive = list(h, n_max, first_batch = 64,
#           growth = 2), Besag-Clifford stopping: each gene runs until a direction has h exceedances
#           (|null| >= |r|) or n_max permutations, in batches of first_batch, first_batch * growth, ...
#           (the batches do not change any result).
# mode      "pair": gene g of X against gene g of Y, both directions (spatialCorrelationGeneExp());
#           "forward": only the direction that permutes X (viladomatCorrelation()); a gene does not fail
#           when its Y is NA or constant: its nulls are then NA (as cor() gives them) and pX is NA;
#           "within": X only, every pair of genes (spatialCorrelationGeneExpWithinSample(); deltaX is the
#           per-gene grid, Y and deltaY are not used); one task per gene whose surrogates are correlated
#           with every other gene. Fixed B only in "forward" and "within".
# state, units    continue an earlier call (its attr(, "state")) for some units (gene indices or names;
#           all if NULL): nPermutations (or adaptive$n_max) extends them by the permutations they lack,
#           which equals a single longer run (prefix property). X, Y, pos, deltas, seed and
#           maxDistPrctile then come from the state.
# chunk     permutations per work item; batch  the largest batch (default: a memory budget, see
#           .stc_max_batch()); noise  "cpp" (default) or "R" (the same normals from R's rnorm(), for
#           tests). None of them changes any result.
# streams   "legacy" (default): the shared draws of the original implementation; "independent" (mode
#           "pair" only): every gene and direction draws its permutations and noise from its own stream,
#           keyed by (seed, gene name, direction, permutation) (src/stc_rng.h; compareSpatial()). The gene
#           names (colnames(X)) must then be unique.
#
# Returns a data.frame with one row per gene ("pair", "forward") or per pair of genes ("within", in
# combn() order): gene (or first, second), r (cor(X, Y) of each gene, as the method computes it), L
# (permutations kept), stop ("cap": n_max or B reached, "exceedances": a direction reached h, "failed"),
# bX, bY (exceedances of each direction in 1..L), pX, pY ((b + 1) / (L + 1), the p-values of fixed-B
# runs), p (the combined Besag-Clifford p-value: max(bX, bY) / L if stopped by exceedances, else
# (max(bX, bY) + 1) / (L + 1)), deltaStarMedianX, deltaStarMedianY (the median delta* of each
# direction), status ("ok" or "failed"), message, and list columns nullX, nullY, deltaStarX, deltaStarY
# (delta values) and, with returnPermutations, permutationsX and permutationsY (N x L). Failed rows have
# NA in every permutation column (an NA row); "forward" rows have NA in the Y columns. attr(, "state")
# holds the session for continuation. The caller's global RNG state is left as it was.
.stc_engine_correlate <- function(X = NULL, Y = NULL, pos = NULL, deltaX = NULL, deltaY = NULL,
                                  nPermutations = 100L, adaptive = NULL, seed = 0,
                                  maxDistPrctile = 0.25, nThreads = 1L, returnPermutations = FALSE,
                                  mode = c("pair", "forward", "within"), state = NULL, units = NULL,
                                  chunk = 16L, batch = NULL, noise = c("cpp", "R"),
                                  streams = c("legacy", "independent")) {
  .stc_local_rng()
  if (is.null(state)) {
    state <- .stc_engine_prepare(X, Y, pos, deltaX, deltaY, seed, maxDistPrctile, nThreads,
                                 returnPermutations, match.arg(mode), chunk, match.arg(noise),
                                 match.arg(streams))
  } else {
    if (!is.environment(state) || is.null(state$session)) stop("state must be attr(, \"state\") of an earlier result")
    if (!missing(nThreads) || !missing(chunk)) {
      .stc_engine_set_threads(state$session, .stc_threads(nThreads), .stc_positive_int(chunk, "chunk"))
    }
  }
  sel <- .stc_engine_select(state, units)
  .stc_engine_extend(state, sel, nPermutations, adaptive, batch)
  out <- .stc_engine_collect(state, sel)
  attr(out, "state") <- state
  out
}

# Session, tasks and units of a new engine run (see .stc_engine_correlate()). keepNulls = FALSE (only with
# independent streams, for compareSpatial()) keeps the nulls and delta* of the current batch only: the
# results are then the exceedance counts and the delta* counts per grid position (.stc_engine_task_results()
# $dstar_count), which is what the adaptive stopping and the summaries need.
.stc_engine_prepare <- function(X, Y, pos, deltaX, deltaY, seed, maxDistPrctile, nThreads,
                                returnPermutations, mode, chunk, noise, streams = "legacy",
                                keepNulls = TRUE) {
  independent <- identical(streams, "independent")
  if (independent && mode != "pair") stop("independent streams are only available for gene-wise comparisons")
  if (!independent && !keepNulls) stop("keepNulls = FALSE needs independent streams")
  X <- .stc_gene_matrix(X, "X")
  N <- nrow(X)
  G <- ncol(X)
  if (mode %in% c("pair", "forward")) {
    Y <- .stc_gene_matrix(Y, "Y")
    if (!identical(dim(Y), dim(X))) stop("X and Y must have the same dimensions (pixels x genes)")
  } else if (G < 2L) {
    stop("the within-sample mode needs at least 2 genes")
  }
  if (N < 2L) stop("at least 2 pixels are needed")
  if (G < 1L) stop("no genes")
  if (is.null(pos)) stop("pos is missing")
  pos <- as.matrix(pos)
  if (nrow(pos) != N || ncol(pos) < 2L) stop("pos must have one row per pixel and 2 columns")
  lat <- suppressWarnings(as.double(pos[, 1]))
  long <- suppressWarnings(as.double(pos[, 2]))
  if (!all(is.finite(lat)) || !all(is.finite(long))) stop("the coordinates must be finite")
  nThreads <- .stc_threads(nThreads)
  chunk <- .stc_positive_int(chunk, "chunk")
  if (independent) {
    if (!is.numeric(seed) || length(seed) != 1L || is.na(suppressWarnings(as.integer(seed))) || seed != round(seed)) {
      stop("seed must be a single integer")
    }
  } else {
    .stc_check_seed(seed, 1)
  }
  if (!is.numeric(maxDistPrctile) || length(maxDistPrctile) != 1L) stop("maxDistPrctile must be a single number")
  gridX <- .stc_delta_grids(deltaX, G, "deltaX")
  gridY <- if (mode == "pair") .stc_delta_grids(deltaY, G, "deltaY") else NULL
  genes <- colnames(X)
  if (is.null(genes)) genes <- as.character(seq_len(G))
  if (independent && (anyNA(genes) || anyDuplicated(genes))) {
    stop("independent streams need unique gene names (colnames(X)): they key the streams")
  }

  # the variogram subsample and, for the legacy streams, the permutation stream (set.seed(seed) under the
  # caller's RNG kinds)
  stream <- if (independent) NULL else .stc_legacy_stream(N, seed)
  ids <- if (independent) .stc_subsample(N, seed) else stream$ids
  # max.dist and the geoR pair table as the method computes them; where that fails (an invalid
  # maxDistPrctile, no pair below max.dist, ...) every gene gets an NA row, as in the R implementation
  plan <- tryCatch({
    prctile <- stats::quantile(stats::dist(cbind(lat[ids], long[ids])), probs = maxDistPrctile)
    .stc_variog_plan(long[ids], lat[ids], prctile)
  }, error = function(e) list(ok = FALSE, reason = conditionMessage(e)))

  noise_R <- identical(noise, "R")
  deltas <- unique(unlist(c(gridX, gridY), use.names = FALSE))
  session <- .stc_engine_new(long, lat, as.integer(ids) - 1L, plan, deltas, as.integer(.stc_cor_mode()),
                             as.double(seed), noise_R, nThreads, chunk, isTRUE(returnPermutations),
                             rng = if (independent) 1L else 0L, keep_nulls = isTRUE(keepNulls))
  grid_index <- function(g) match(g, deltas) - 1L

  if (mode == "pair") {
    pool <- cbind(X, Y)
    # the observed r of each direction, as viladomatCorrelation() computes it: cor(X, Y) and cor(Y, X)
    rX <- suppressWarnings(vapply(seq_len(G), function(g) stats::cor(X[, g], Y[, g]), 0))
    rY <- suppressWarnings(vapply(seq_len(G), function(g) stats::cor(Y[, g], X[, g]), 0))
    task_source <- as.vector(rbind(seq_len(G), G + seq_len(G))) - 1L     # X_1, Y_1, X_2, Y_2, ...
    task_targets <- as.list(as.vector(rbind(G + seq_len(G), seq_len(G))) - 1L)
    task_grid <- lapply(as.vector(rbind(gridX, gridY), "list"), grid_index)
    task_rabs <- as.list(abs(as.vector(rbind(rX, rY))))
    task_unit <- rep(seq_len(G), each = 2L) - 1L
    fail_on_dir <- rep(TRUE, G)
    r <- list(X = rX, Y = rY)
  } else if (mode == "forward") {
    pool <- cbind(X, Y)
    rX <- suppressWarnings(vapply(seq_len(G), function(g) stats::cor(X[, g], Y[, g]), 0))
    task_source <- seq_len(G) - 1L
    task_targets <- as.list(G + seq_len(G) - 1L)
    task_grid <- lapply(gridX, grid_index)
    task_rabs <- as.list(abs(rX))  # NA when r is NA: then no null counts as an exceedance
    task_unit <- seq_len(G) - 1L
    fail_on_dir <- rep(FALSE, G)  # an NA or constant Y gives NA nulls, not a failure
    r <- list(X = rX)
  } else {
    pool <- X
    # rm[i, j] = cor(X_i, X_j): pair (i, j) of spatialCorrelation() uses cor(X_i, X_j) when permuting i.
    # cor(X, X) with y given computes every element with the arithmetic of cor(X[, i], X[, j]) (R's
    # cov.c, use = "everything": each pair of columns on its own, as for two vectors), so it equals the
    # pairwise calls bit for bit, in one call instead of G^2.
    rm <- unname(suppressWarnings(stats::cor(X, X)))
    task_source <- seq_len(G) - 1L
    task_targets <- lapply(seq_len(G), function(i) setdiff(seq_len(G), i) - 1L)
    task_grid <- lapply(gridX, grid_index)
    task_rabs <- lapply(seq_len(G), function(i) abs(rm[i, -i]))
    task_unit <- seq_len(G) - 1L
    fail_on_dir <- rep(FALSE, G)
    r <- rm
  }
  # stream keys (independent streams): task 2g - 1 permutes X_g (direction 1), task 2g permutes Y_g (2)
  info <- .stc_engine_define(session, pool, as.integer(task_source), task_grid,
                             lapply(task_targets, as.integer), lapply(task_rabs, as.double),
                             as.integer(task_unit), fail_on_dir,
                             task_names = if (independent) rep(enc2utf8(genes), each = 2L),
                             task_dirs = if (independent) rep(c(1L, 2L), G))
  state <- new.env(parent = emptyenv())
  state$session <- session
  state$stream <- stream
  state$streams <- streams
  state$ids <- ids
  state$mode <- mode
  state$N <- N
  state$G <- G
  state$genes <- genes
  state$gridX <- gridX
  state$gridY <- gridY
  state$r <- r
  state$seed <- seed
  state$noise_R <- noise_R
  state$kmax <- info$kmax
  state$keep <- isTRUE(returnPermutations)
  state$plan <- plan
  state$deltas <- deltas
  state
}

# Units (genes) selected by index or name; all when NULL.
.stc_engine_select <- function(state, units) {
  if (is.null(units)) return(seq_len(state$G))
  sel <- if (is.character(units)) match(units, state$genes) else suppressWarnings(as.integer(units))
  if (!length(sel) || anyNA(sel) || any(sel < 1L | sel > state$G) || anyDuplicated(sel)) {
    stop("units must be distinct gene indices or names of the session")
  }
  sel
}

# Run batches until every selected unit has n_max permutations (fixed B: n_max = nPermutations, h = Inf),
# has stopped by exceedances, or has failed. Units with fewer permutations go first, so units at
# different lengths (a continuation) are brought to the same length before they share batches.
# progress: NULL, or a reporter (see .stc_progress() in R/compareSpatial.R) whose $batch(u, group, b_from,
# b_to) is called before every batch (u: .stc_engine_units()), $tick(done) by the engine while a batch runs,
# and $finish(u) at the end.
.stc_engine_extend <- function(state, units, nPermutations = NULL, adaptive = NULL, batch = NULL,
                               progress = NULL) {
  if (is.null(adaptive)) {
    n_max <- .stc_positive_int(nPermutations, "nPermutations")
    h <- Inf
    first <- NULL
    growth <- 1
  } else {
    if (state$mode != "pair") stop("adaptive stopping is only available for gene-wise comparisons (mode = \"pair\")")
    if (!is.list(adaptive)) stop("adaptive must be a list(h, n_max, first_batch, growth)")
    h <- as.double(adaptive$h)
    if (length(h) != 1L || is.na(h) || h < 1) stop("adaptive$h must be at least 1 (Inf: no stopping)")
    n_max <- .stc_positive_int(adaptive$n_max, "adaptive$n_max")
    first <- if (is.null(adaptive$first_batch)) 64L else .stc_positive_int(adaptive$first_batch, "adaptive$first_batch")
    growth <- if (is.null(adaptive$growth)) 2 else as.double(adaptive$growth)
    if (length(growth) != 1L || !is.finite(growth) || growth < 1) stop("adaptive$growth must be at least 1")
  }
  # the legacy noise of permutation b is set.seed(seed + b): seed + n_max must be a valid integer
  if (!is.null(state$stream)) .stc_check_seed(state$seed, n_max)
  max_batch <- if (is.null(batch)) .stc_max_batch(state) else .stc_positive_int(batch, "batch")
  step <- 0
  repeat {
    u <- .stc_engine_units(state$session)
    len <- u$len[units]
    runnable <- u$state[units] != 3L & len < n_max &
      vapply(u$counts[units], function(cn) all(cn < h), NA)
    if (!any(runnable)) break
    len0 <- min(len[runnable])
    group <- units[runnable & len == len0]
    b_from <- len0 + 1L
    size <- if (is.null(first)) max_batch else min(max_batch, max(1, floor(first * growth^step)))
    b_to <- as.integer(min(n_max, b_from + size - 1))
    # independent streams: the workers draw their own permutations and noise
    perm <- if (is.null(state$stream)) NULL else .stc_stream_perms(state$stream, b_from, b_to)
    noise <- if (state$noise_R) .stc_stream_noise(state$stream, b_from, b_to, state$kmax) else NULL
    if (!is.null(progress)) progress$batch(u, group, b_from, b_to)
    .stc_engine_run(state$session, group - 1L, b_from, b_to, perm, noise, h, n_max,
                    if (is.null(progress)) NULL else progress$tick)
    step <- step + 1
  }
  if (!is.null(progress)) progress$finish(u)
  invisible(state)
}

.stc_stop_reason <- function(st) c("active", "exceedances", "cap", "failed")[st + 1L]

# p-values of a direction and of a unit from exceedance counts at L (see .stc_engine_correlate()).
.stc_p_direction <- function(b, L) (b + 1) / (L + 1)
.stc_p_combined <- function(bmax, L, stopped_h) ifelse(stopped_h, bmax / L, (bmax + 1) / (L + 1))

.stc_engine_collect <- function(state, units) {
  u <- .stc_engine_units(state$session)
  switch(state$mode, pair = .stc_collect_pair(state, units, u), forward = .stc_collect_forward(state, units, u),
         within = .stc_collect_within(state, units, u))
}

.stc_collect_pair <- function(state, units, u) {
  n <- length(units)
  tr <- .stc_engine_task_results(state$session, as.integer(as.vector(rbind(2L * units - 2L, 2L * units - 1L))),
                                 state$keep)
  st <- u$state[units]
  ok <- st != 3L
  nullX <- nullY <- dsX <- dsY <- permX <- permY <- rep(list(NA), n)
  L <- bX <- bY <- rep(NA_integer_, n)
  medX <- medY <- rep(NA_real_, n)
  message <- rep("", n)
  for (q in seq_len(n)) {
    g <- units[q]
    if (!ok[q]) {
      ft <- u$fail_task[g]
      dir <- if (!is.na(ft) && ft %% 2L == 1L) "permuting Y" else "permuting X"
      message[q] <- paste0(dir, ": ", u$message[g])
      next
    }
    tX <- tr[[2L * q - 1L]]
    tY <- tr[[2L * q]]
    L[q] <- u$len[g]
    nullX[[q]] <- tX$nulls[, 1L]
    nullY[[q]] <- tY$nulls[, 1L]
    dsX[[q]] <- state$gridX[[g]][tX$dstar]
    dsY[[q]] <- state$gridY[[g]][tY$dstar]
    medX[q] <- stats::median(dsX[[q]])
    medY[q] <- stats::median(dsY[[q]])
    bX[q] <- u$counts[[g]][1L]
    bY[q] <- u$counts[[g]][2L]
    if (state$keep) {
      permX[[q]] <- tX$surrogates
      permY[[q]] <- tY$surrogates
    }
  }
  res <- data.frame(gene = state$genes[units], r = state$r$X[units], L = L,
                    stop = .stc_stop_reason(st), bX = bX, bY = bY,
                    pX = .stc_p_direction(bX, L), pY = .stc_p_direction(bY, L),
                    p = .stc_p_combined(pmax(bX, bY), L, st == 1L),
                    deltaStarMedianX = medX, deltaStarMedianY = medY,
                    status = ifelse(ok, "ok", "failed"), message = message, stringsAsFactors = FALSE)
  res$nullX <- I(nullX)
  res$nullY <- I(nullY)
  res$deltaStarX <- I(dsX)
  res$deltaStarY <- I(dsY)
  if (state$keep) {
    res$permutationsX <- I(permX)
    res$permutationsY <- I(permY)
  }
  rownames(res) <- make.unique(state$genes[units])
  res
}

# One direction (permute X, correlate with Y). A unit fails only through X (or the plan, or a smoother);
# an NA or constant Y leaves the surrogates and delta* intact and makes the nulls NA, and an NA in the
# nulls or in r makes pX NA (sum(abs(null) >= abs(r)) is NA in R). Such rows have status "ok" and a
# message.
.stc_collect_forward <- function(state, units, u) {
  n <- length(units)
  tr <- .stc_engine_task_results(state$session, as.integer(units - 1L), state$keep)
  st <- u$state[units]
  ok <- st != 3L
  nullX <- dsX <- permX <- rep(list(NA), n)
  L <- bX <- rep(NA_integer_, n)
  medX <- rep(NA_real_, n)
  message <- rep("", n)
  for (q in seq_len(n)) {
    g <- units[q]
    if (!ok[q]) {
      message[q] <- paste0("permuting X: ", u$message[g])
      next
    }
    tX <- tr[[q]]
    L[q] <- u$len[g]
    nullX[[q]] <- tX$nulls[, 1L]
    dsX[[q]] <- state$gridX[[g]][tX$dstar]
    medX[q] <- stats::median(dsX[[q]])
    if (state$keep) permX[[q]] <- tX$surrogates
    ts <- tX$target_status[1L]
    if (ts != 0L || anyNA(nullX[[q]]) || is.na(state$r$X[g])) {
      message[q] <- if (ts == 2L) {
        "the values correlated with the permutations contain NA, NaN or Inf"
      } else if (ts == 4L) {
        "the values correlated with the permutations are constant (zero variance)"
      } else if (!is.na(tX$dir_fail_b[1L])) {
        sprintf("permutation %d: a null correlation is NA", tX$dir_fail_b[1L])
      } else {
        "the observed correlation is NA"
      }
    } else {
      bX[q] <- u$counts[[g]][1L]
    }
  }
  res <- data.frame(gene = state$genes[units], r = state$r$X[units], L = L,
                    stop = .stc_stop_reason(st), bX = bX, bY = NA_integer_,
                    pX = .stc_p_direction(bX, L), pY = NA_real_, p = .stc_p_direction(bX, L),
                    deltaStarMedianX = medX, deltaStarMedianY = NA_real_,
                    status = ifelse(ok, "ok", "failed"), message = message, stringsAsFactors = FALSE)
  res$nullX <- I(nullX)
  res$nullY <- I(rep(list(NA), n))
  res$deltaStarX <- I(dsX)
  res$deltaStarY <- I(rep(list(NA), n))
  if (state$keep) {
    res$permutationsX <- I(permX)
    res$permutationsY <- I(rep(list(NA), n))
  }
  rownames(res) <- make.unique(state$genes[units])
  res
}

# Pair (i, j), i < j, takes the X columns from gene i's task (its surrogates correlated with gene j) and
# the Y columns from gene j's task, over the first min(L_i, L_j) permutations. The pairs are filled gene
# by gene, not one at a time: the number of pairs grows with the square of the number of genes.
.stc_collect_within <- function(state, units, u) {
  units <- sort(units)
  pairs <- utils::combn(units, 2L)
  tr <- .stc_engine_task_results(state$session, as.integer(units - 1L), state$keep)
  np <- ncol(pairs)
  gi <- pairs[1L, ]
  gj <- pairs[2L, ]
  # With sorted units gi < gj, so gene gj is target gj - 1 of gene gi (a gene's targets are all other
  # genes, in order) and gene gi is target gi of gene gj.
  rX <- state$r[cbind(gi, gj)]
  rY <- state$r[cbind(gj, gi)]
  Lq <- pmin(u$len[gi], u$len[gj])
  failed <- u$state == 3L
  as_first <- split(seq_len(np), factor(gi, levels = units))   # pairs of each gene, by position in units
  as_second <- split(seq_len(np), factor(gj, levels = units))
  # first permutation whose null correlation is NA, in each direction (NA: none)
  failX <- failY <- rep(NA_integer_, np)
  for (a in seq_along(units)) {
    if (failed[units[a]]) next
    qa <- as_first[[a]]
    qb <- as_second[[a]]
    failX[qa] <- tr[[a]]$dir_fail_b[gj[qa] - 1L]
    failY[qb] <- tr[[a]]$dir_fail_b[gi[qb]]
  }
  bad_i <- failed[gi]
  bad_j <- failed[gj]
  gene_msg <- paste0(state$genes, ": ", u$message)
  message <- rep("", np)
  message[bad_i] <- gene_msg[gi[bad_i]]
  message[bad_j & !bad_i] <- gene_msg[gj[bad_j & !bad_i]]
  both <- bad_i & bad_j
  message[both] <- paste(gene_msg[gi[both]], gene_msg[gj[both]], sep = "; ")
  fx <- !bad_i & !bad_j & !is.na(failX) & failX <= Lq
  fy <- !bad_i & !bad_j & !fx & !is.na(failY) & failY <= Lq
  message[fx] <- sprintf("permuting %s, permutation %d: the null correlation with %s is NA",
                         state$genes[gi[fx]], failX[fx], state$genes[gj[fx]])
  message[fy] <- sprintf("permuting %s, permutation %d: the null correlation with %s is NA",
                         state$genes[gj[fy]], failY[fy], state$genes[gi[fy]])
  ok <- !(bad_i | bad_j | fx | fy)
  status <- ifelse(ok, "ok", "failed")
  L <- rep(NA_integer_, np)
  L[ok] <- Lq[ok]

  nullX <- nullY <- dsX <- dsY <- permX <- permY <- rep(list(NA), np)
  bX <- bY <- rep(NA_integer_, np)
  medX <- medY <- rep(NA_real_, np)
  # the columns of a matrix as a list of vectors (split() with a ready-made factor: no conversion)
  columns <- function(M) {
    nc <- ncol(M)
    f <- structure(rep(seq_len(nc), each = nrow(M)), levels = as.character(seq_len(nc)), class = "factor")
    unname(split.default(M, f))
  }
  for (a in seq_along(units)) {
    g <- units[a]
    if (failed[g]) next
    task <- tr[[a]]
    for (first in c(TRUE, FALSE)) {
      # gene g permuted: as the first gene of a pair (X columns) or as the second (Y columns)
      q <- if (first) as_first[[a]] else as_second[[a]]
      q <- q[ok[q]]
      for (len in unique(Lq[q])) {
        s <- q[Lq[q] == len]
        target <- if (first) gj[s] - 1L else gi[s]
        r_abs <- abs(if (first) rX[s] else rY[s])
        M <- task$nulls[seq_len(len), target, drop = FALSE]
        nulls <- columns(M)
        b <- as.integer(colSums(abs(M) >= rep(r_abs, each = len)))
        ds <- state$gridX[[g]][task$dstar[seq_len(len)]]  # one vector (and median) shared by the pairs
        med <- stats::median(ds)
        if (first) {
          nullX[s] <- nulls
          bX[s] <- b
          dsX[s] <- list(ds)
          medX[s] <- med
          if (state$keep) permX[s] <- list(task$surrogates)
        } else {
          nullY[s] <- nulls
          bY[s] <- b
          dsY[s] <- list(ds)
          medY[s] <- med
          if (state$keep) permY[s] <- list(task$surrogates)
        }
      }
    }
  }
  st <- ifelse(ok, 2L, 3L)
  res <- data.frame(first = state$genes[pairs[1L, ]], second = state$genes[pairs[2L, ]], r = rX, L = L,
                    stop = .stc_stop_reason(st), bX = bX, bY = bY,
                    pX = .stc_p_direction(bX, L), pY = .stc_p_direction(bY, L),
                    p = .stc_p_combined(pmax(bX, bY), L, FALSE),
                    deltaStarMedianX = medX, deltaStarMedianY = medY,
                    status = status, message = message, stringsAsFactors = FALSE)
  res$nullX <- I(nullX)
  res$nullY <- I(nullY)
  res$deltaStarX <- I(dsX)
  res$deltaStarY <- I(dsY)
  if (state$keep) {
    res$permutationsX <- I(permX)
    res$permutationsY <- I(permY)
  }
  res
}

# ---------------------------------------------------------------------------------------------------
# Helpers of the exported functions (R/spatialCorrelation.R, R/iterativePermutations.R)
# ---------------------------------------------------------------------------------------------------

# A numeric vector from a vector or a one-row or one-column matrix.
.stc_values <- function(x, name) {
  if (is.null(x)) stop(sprintf("%s is missing", name))
  if (!is.null(dim(x))) {
    if (length(dim(x)) != 2L || min(dim(x)) != 1L) {
      stop(sprintf("%s must be a numeric vector (or a matrix with one row or one column)", name))
    }
    x <- as.matrix(x)
    x <- as.vector(if (nrow(x) == 1L) x[1L, ] else x[, 1L])
  }
  if (is.factor(x) || !(is.numeric(x) || is.logical(x))) stop(sprintf("%s must be numeric", name))
  as.double(x)
}

# nPermutations of the fixed-B functions.
.stc_check_nperm <- function(nPermutations) {
  if (!is.numeric(nPermutations) || length(nPermutations) != 1L || is.na(nPermutations) ||
      nPermutations < 1 || nPermutations != round(nPermutations) || nPermutations > .Machine$integer.max) {
    stop("nPermutations must be a positive integer")
  }
  as.integer(nPermutations)
}

# One delta grid per gene from a list (or vector) with one element per gene, as the gene-wise functions
# index it (delta[[i]] for gene i); NULL gives every gene the default grid.
.stc_gene_deltas <- function(delta, G, name) {
  if (is.null(delta)) return(rep(list(NULL), G))
  if (length(delta) != G) {
    stop(sprintf("%s must be a list with one element (a numeric vector of deltas) per gene: %d genes, %d elements",
                 name, G, length(delta)))
  }
  lapply(seq_len(G), function(i) delta[[i]])
}

# The two SpatialExperiment objects of a gene-wise comparison: shared pixels (in the order of the first
# object), their coordinates, and pixels x genes matrices of the assay (genes of the first object, taken
# by name from both).
.stc_pair_input <- function(input, assayName) {
  if (length(input) < 2L) stop("input must be a list of two SpatialExperiment objects")
  source <- input[[1]]
  target <- input[[2]]
  if (is.null(assayName)) assayName <- 1
  genes <- rownames(source)
  if (is.null(genes) || !length(genes)) stop("the first SpatialExperiment object has no row names (genes)")
  shared <- intersect(rownames(SpatialExperiment::spatialCoords(source)),
                      rownames(SpatialExperiment::spatialCoords(target)))
  if (length(shared) < 3L) {
    stop(sprintf("the two SpatialExperiment objects share %d pixel(s); at least 3 are needed", length(shared)))
  }
  pos <- SpatialExperiment::spatialCoords(source)[shared, , drop = FALSE]
  a <- SummarizedExperiment::assay(source, assayName)
  b <- SummarizedExperiment::assay(target, assayName)
  missing_genes <- setdiff(genes, rownames(b))
  if (length(missing_genes)) {
    stop(sprintf("%d gene(s) of the first object are missing from the second, for example %s",
                 length(missing_genes), missing_genes[1]))
  }
  X <- t(as.matrix(a[genes, shared, drop = FALSE]))
  Y <- t(as.matrix(b[genes, shared, drop = FALSE]))
  storage.mode(X) <- "double"
  storage.mode(Y) <- "double"
  colnames(X) <- colnames(Y) <- genes
  list(genes = genes, pos = pos, X = X, Y = Y)
}

# cor.test(x, y) for the column pairs (X[, ix[k]], Y[, iy[k]]): the estimate and the naive p-value, as
# cor.test() computes them. When both columns are finite and there are at least 3 pixels, cor.test() uses
# every pixel: its estimate is r = cor(x, y) and its p-value is 2 * min(pt(t, df), pt(t, df, lower.tail =
# FALSE)) with df = N - 2 and t = sqrt(df) * r / sqrt(1 - r^2). Those pairs are computed here all at once
# with exactly that arithmetic; r_pairs, if given, is cor(X[, ix[k]], Y[, iy[k]]) of every pair as R's
# cor() computed it elsewhere (otherwise it is computed here). The other pairs (missing or infinite values,
# fewer than 3 pixels) go through cor.test() itself. Warnings (a zero standard deviation) are muffled,
# because such a gene also gets an NA row whose warning names it; where cor.test() fails (fewer than 3
# complete pairs), r and p are NA and the error is kept in msg.
.stc_cor_tests <- function(X, Y, ix = seq_len(ncol(X)), iy = ix, r_pairs = NULL) {
  n <- length(ix)
  N <- nrow(X)
  r <- p <- rep(NA_real_, n)
  msg <- rep("", n)
  finite <- function(M) vapply(seq_len(ncol(M)), function(j) all(is.finite(M[, j])), NA)
  fx <- finite(X)
  fy <- if (identical(X, Y)) fx else finite(Y)
  fast <- N >= 3L & fx[ix] & fy[iy]
  if (any(fast)) {
    r[fast] <- if (is.null(r_pairs)) {
      suppressWarnings(vapply(which(fast), function(k) stats::cor(X[, ix[k]], Y[, iy[k]]), 0))
    } else {
      r_pairs[fast]
    }
    df <- N - 2L
    tstat <- sqrt(df) * r[fast] / sqrt(1 - r[fast]^2)
    p[fast] <- 2 * pmin(stats::pt(tstat, df), stats::pt(tstat, df, lower.tail = FALSE))
  }
  for (i in which(!fast)) {
    ct <- tryCatch(suppressWarnings(stats::cor.test(X[, ix[i]], Y[, iy[i]])), error = function(e) e)
    if (inherits(ct, "error")) {
      msg[i] <- paste("cor.test() failed:", conditionMessage(ct))
    } else {
      r[i] <- unname(ct$estimate)
      p[i] <- ct$p.value
    }
  }
  list(r = r, p = p, msg = msg)
}

# The table of the gene-wise functions from cor.test() results and an engine result ("pair" or
# "within" rows): numeric columns correlationCoef, pValueNaive, pValuePermuteX/Y, deltaStarMedianX/Y,
# and AsIs list columns deltaStarX/Y (delta* of every permutation), nullCorrelationsX/Y (B x 1
# matrices) and, with keep, permutationsX/Y (N x B matrices). An NA row has NA in every column computed
# from permutations (NA elements in the list columns).
.stc_result_table <- function(naive, e, keep, row_names) {
  n <- nrow(e)
  ok <- e$status == "ok"
  pick <- function(v) {
    v <- unclass(v)
    v[!ok] <- list(NA)
    v
  }
  # B x 1 matrices (dim<- gives what matrix(x, ncol = 1L) gives, without its argument checks)
  as_col <- function(v) {
    out <- rep(list(NA), n)
    out[ok] <- lapply(unclass(v)[ok], function(x) {
      dim(x) <- c(length(x), 1L)
      x
    })
    out
  }
  out <- data.frame(correlationCoef = as.double(naive$r), pValueNaive = as.double(naive$p),
                    pValuePermuteX = ifelse(ok, as.double(e$pX), NA_real_),
                    pValuePermuteY = ifelse(ok, as.double(e$pY), NA_real_),
                    deltaStarMedianX = ifelse(ok, as.double(e$deltaStarMedianX), NA_real_),
                    deltaStarMedianY = ifelse(ok, as.double(e$deltaStarMedianY), NA_real_))
  out$deltaStarX <- I(pick(e$deltaStarX))
  out$deltaStarY <- I(pick(e$deltaStarY))
  out$nullCorrelationsX <- I(as_col(e$nullX))
  out$nullCorrelationsY <- I(as_col(e$nullY))
  if (keep) {
    out$permutationsX <- I(pick(e$permutationsX))
    out$permutationsY <- I(pick(e$permutationsY))
  }
  rownames(out) <- row_names
  out
}

# One warning() per NA row (never print()): fun, the row's label (NULL for a single comparison), and why.
.stc_warn_na_rows <- function(fun, labels, e, naive = NULL) {
  bad <- which(e$status != "ok")
  for (i in bad) {
    why <- e$message[i]
    if (!is.null(naive) && nzchar(naive$msg[i])) why <- paste0(naive$msg[i], "; ", why)
    warning(sprintf("%s: %sno permutation p-values (NA row): %s", fun,
                    if (is.null(labels)) "" else paste0(labels[i], ": "), why), call. = FALSE)
  }
  invisible(length(bad))
}

# Elapsed seconds since t0 (proc.time()), for the verbose end messages.
.stc_elapsed <- function(t0) sprintf("%.1f s", (proc.time() - t0)[["elapsed"]])
