# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.stc_variog_pairs <- function(x1, x2, max_dist, lims, keep_nugget, pairs_min = 2L) {
    .Call(`_STcompare_stc_variog_pairs`, x1, x2, max_dist, lims, keep_nugget, pairs_min)
}

.stc_variog_eval <- function(plan, Z, tile = 16L) {
    .Call(`_STcompare_stc_variog_eval`, plan, Z, tile)
}

.stc_smoother <- function(x1, x2, delta, maxk = 300L, build_operator = TRUE) {
    .Call(`_STcompare_stc_smoother`, x1, x2, delta, maxk, build_operator)
}

.stc_smoother_fitted_exact <- function(x1, x2, y, delta, maxk = 300L) {
    .Call(`_STcompare_stc_smoother_fitted_exact`, x1, x2, y, delta, maxk)
}

.stc_smoother_apply <- function(op, Y, rows = NULL) {
    .Call(`_STcompare_stc_smoother_apply`, op, Y, rows)
}

.stc_lecuyer_seed <- function(seed) {
    .Call(`_STcompare_stc_lecuyer_seed`, seed)
}

.stc_lecuyer_runif <- function(seed, n) {
    .Call(`_STcompare_stc_lecuyer_runif`, seed, n)
}

.stc_lecuyer_rnorm <- function(seed, n) {
    .Call(`_STcompare_stc_lecuyer_rnorm`, seed, n)
}

.stc_legacy_noise <- function(seed, N, K) {
    .Call(`_STcompare_stc_legacy_noise`, seed, N, K)
}

.stc_cor_cols <- function(X, y, mode = 0L) {
    .Call(`_STcompare_stc_cor_cols`, X, y, mode)
}

.stc_ols <- function(x, y) {
    .Call(`_STcompare_stc_ols`, x, y)
}

