# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.stc_engine_new <- function(x1, x2, ids, plan, deltas, cor_mode, seed, noise_supplied, n_threads, chunk, keep_surrogates) {
    .Call(`_STcompare_stc_engine_new`, x1, x2, ids, plan, deltas, cor_mode, seed, noise_supplied, n_threads, chunk, keep_surrogates)
}

.stc_engine_deltas <- function(session) {
    .Call(`_STcompare_stc_engine_deltas`, session)
}

.stc_engine_define <- function(session, pool, task_source, task_grid, task_targets, task_rabs, task_unit, unit_fail_on_dir) {
    .Call(`_STcompare_stc_engine_define`, session, pool, task_source, task_grid, task_targets, task_rabs, task_unit, unit_fail_on_dir)
}

.stc_engine_run <- function(session, units, b_from, b_to, perm, noise, h, n_max) {
    invisible(.Call(`_STcompare_stc_engine_run`, session, units, b_from, b_to, perm, noise, h, n_max))
}

.stc_engine_units <- function(session) {
    .Call(`_STcompare_stc_engine_units`, session)
}

.stc_engine_task_results <- function(session, tasks, surrogates) {
    .Call(`_STcompare_stc_engine_task_results`, session, tasks, surrogates)
}

.stc_engine_set_threads <- function(session, n_threads, chunk) {
    invisible(.Call(`_STcompare_stc_engine_set_threads`, session, n_threads, chunk))
}

.stc_parallel_selftest <- function(n_items, n_threads, fail_item = -1L, sleep_ms = 0L) {
    .Call(`_STcompare_stc_parallel_selftest`, n_items, n_threads, fail_item, sleep_ms)
}

.stc_variog_pairs <- function(x1, x2, max_dist, lims, keep_nugget, pairs_min = 2L) {
    .Call(`_STcompare_stc_variog_pairs`, x1, x2, max_dist, lims, keep_nugget, pairs_min)
}

.stc_variog_eval <- function(plan, Z, tile = 16L) {
    .Call(`_STcompare_stc_variog_eval`, plan, Z, tile)
}

.stc_smoother <- function(x1, x2, delta, maxk = 300L, build_operator = TRUE) {
    .Call(`_STcompare_stc_smoother`, x1, x2, delta, maxk, build_operator)
}

.stc_smoother_fitted_exact <- function(x1, x2, y, delta, maxk = 300L) {
    .Call(`_STcompare_stc_smoother_fitted_exact`, x1, x2, y, delta, maxk)
}

.stc_smoother_apply <- function(op, Y, rows = NULL, blocked = FALSE) {
    .Call(`_STcompare_stc_smoother_apply`, op, Y, rows, blocked)
}

.stc_lecuyer_seed <- function(seed) {
    .Call(`_STcompare_stc_lecuyer_seed`, seed)
}

.stc_lecuyer_runif <- function(seed, n) {
    .Call(`_STcompare_stc_lecuyer_runif`, seed, n)
}

.stc_lecuyer_rnorm <- function(seed, n) {
    .Call(`_STcompare_stc_lecuyer_rnorm`, seed, n)
}

.stc_legacy_noise <- function(seed, N, K) {
    .Call(`_STcompare_stc_legacy_noise`, seed, N, K)
}

.stc_cor_cols <- function(X, y, mode = 0L) {
    .Call(`_STcompare_stc_cor_cols`, X, y, mode)
}

.stc_ols <- function(x, y) {
    .Call(`_STcompare_stc_ols`, x, y)
}

