# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.variogram_pairs <- function(x, y, maxdist, lims) {
    .Call(`_STcompare_variogram_pairs`, x, y, maxdist, lims)
}

.variogram_sums <- function(Z, pi, pj, pb, nbins, nthreads = 1L) {
    .Call(`_STcompare_variogram_sums`, Z, pi, pj, pb, nbins, nthreads)
}

.test_worker_exception <- function(nthreads) {
    .Call(`_STcompare_test_worker_exception`, nthreads)
}

